import { useState, useEffect } from 'react'
import PetsPage from './pages/PetsPage'
import './App.css'

function App() {
  const [isClientGenerated, setIsClientGenerated] = useState(false);

  useEffect(() => {
    // Check if the client has been generated by attempting to import it
    import('./api/generated/client')
      .then(() => {
        setIsClientGenerated(true);
      })
      .catch((error) => {
        console.warn('API client not generated yet:', error);
        setIsClientGenerated(false);
      });
  }, []);

  return (
    <div className="app">
      <header className="app-header">
        <h1>OpenAPI Tools Demo</h1>
        <p>Using @arthurmtro/openapi-tools-client with React</p>
        {!isClientGenerated && (
          <div className="warning">
            <strong>Note:</strong> API client not generated yet. Run <code>npm run generate-client</code> to generate the client.
          </div>
        )}
      </header>

      <main>
        <PetsPage />
      </main>

      <footer className="app-footer">
        <p>
          This example demonstrates using the OpenAPI Tools client library with React.
          The client is {isClientGenerated ? 'generated' : 'not generated yet'}.
        </p>
      </footer>
    </div>
  )
}

export default App